In [1]:
import sys
import os

def _getThreads():
    """ Returns the number of available threads on a posix/win based system """
    if sys.platform == 'win32':
        return (int)(os.environ['NUMBER_OF_PROCESSORS'])
    else:
        return (int)(os.popen('grep -c cores /proc/cpuinfo').read())

_getThreads()

12

In [2]:
import numpy as np
import pandas as pd

In [3]:
def increment_lc():
    global KG_leaf_counter
    KG_leaf_counter+=1
    return KG_leaf_counter

In [4]:
KG_leaf_counter = 0

# Initialize empty DF
COV=pd.DataFrame()

# Add empty column
COV[increment_lc()] = ''

# Add empty row and drop initial row
COV = COV.append([''], ignore_index=True)
COV.drop([0], axis=1, inplace = True)

In [5]:
# Reindex so we start from 1
COV.index = np.arange(1, len(COV)+1)
print(COV.index)
COV

Int64Index([1], dtype='int64')


1
1  NaN

In [6]:
# Add two empty columns (for partinioed leaf)
COV[increment_lc()] = ''
COV[increment_lc()] = ''
COV

1 2 3
1  NaN

In [7]:
# Create the row we will insert from the new leaf
# This will be done by obtaining the covariances 
# and putting them in a dictionary s pictured
val1 =[0.0, 1.1, 2.2, 3.3, 4.4, 5,5]
row1={i:val1[i] for i in COV.columns}

val2 =[10.0, 11.1, 12.2, 13.3, 14.4, 15,5]
row2={i:val2[i] for i in COV.columns}

print("row1 =", row1)
print("row2 =", row2)

row1 = {1: 1.1, 2: 2.2, 3: 3.3}
row2 = {1: 11.1, 2: 12.2, 3: 13.3}


In [8]:
# Create rows as pandas series with index-names
s1 = pd.Series(row1, name=COV.index.max()+1)
s2 = pd.Series(row2, name=COV.index.max()+2)

In [9]:
# Append the two new rows
COV = COV.append(s1)
COV = COV.append(s2)

In [10]:
COV

1     2     3
1   NaN            
2   1.1   2.2   3.3
3  11.1  12.2  13.3

In [11]:
# Delete row 1
COV.drop([1], inplace = True)

#Delete column 1
COV.drop([1], axis=1, inplace = True)

In [12]:
COV

2     3
2   2.2   3.3
3  12.2  13.3

In [13]:
# Add 2 empty columns
COV[increment_lc()] = ''
COV[increment_lc()] = ''

In [14]:
COV

2     3 4 5
2   2.2   3.3    
3  12.2  13.3

In [15]:
#Create 2 extra rows
val1 =[0.0, 1.1, 2.2, 3.3, 4.4, 5,5]
row1={i:val1[i] for i in COV.columns}

val2 =[10.0, 11.1, 12.2, 13.3, 14.4, 15,5]
row2={i:val2[i] for i in COV.columns}

# Create rows as pandas series with index-names
s1 = pd.Series(row1, name=COV.index.max()+1)
s2 = pd.Series(row2, name=COV.index.max()+2)

In [16]:
# Append the two new rows
COV = COV.append(s1)
COV = COV.append(s2)
COV

2     3     4   5
2   2.2   3.3          
3  12.2  13.3          
4   2.2   3.3   4.4   5
5  12.2  13.3  14.4  15

In [17]:
# Create rows as pandas series with index-names
s1 = pd.Series(name=COV.index.max()+1)
s2 = pd.Series(name=COV.index.max()+2)

C:\Users\Ricardo\Anaconda3\envs\insight-prj\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  
C:\Users\Ricardo\Anaconda3\envs\insight-prj\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
COV = COV.append(s1)
COV = COV.append(s2)
COV

2     3     4    5
2   2.2   3.3           
3  12.2  13.3           
4   2.2   3.3   4.4    5
5  12.2  13.3  14.4   15
6   NaN   NaN   NaN  NaN
7   NaN   NaN   NaN  NaN

In [20]:
M = COV.to_numpy()

In [24]:
M[0][2]=5.2

In [25]:
COV

2     3     4    5
2   2.2   3.3   5.2  5.2
3  12.2  13.3           
4   2.2   3.3   4.4    5
5  12.2  13.3  14.4   15
6   NaN   NaN   NaN  NaN
7   NaN   NaN   NaN  NaN

In [88]:
const_vec = [{0: 1}, {0: 0, 1: 0}]

In [89]:
const_str = []

for d in const_vec:
    d_str=''
    for k in d.keys():
        d_str+=str(d[k])
    const_str.append(d_str)

In [90]:
const_str

['1', '00']

In [91]:
s1_const = {0: 0, 1: 1, 2: 0}

In [92]:
s1_const_str = ''
for k in s1_const.keys():
    s1_const_str+=str(s1_const[k])

In [93]:
s1_const_str

'010'

In [94]:
from jellyfish import levenshtein_distance as l_dist
dist = np.array([l_dist(s1_const_str, string) for string in const_str])

In [95]:
dist

array([2, 1])

In [106]:
l_dist('000','111')

3

In [101]:
f = np.array([1,2,3])

In [102]:
1+f

array([2, 3, 4])

In [68]:
col = 2**2 * np.exp(-1*np.square(dist*(1/(2))))

In [69]:
col.append(1.0)
col.append(2**2 * np.exp(-1*np.square(dist*(1/(2)))))

array([1.47151776, 3.11520313])

In [62]:
M

array([[2.2, 3.3, 5.2, 5.2],
       [12.2, 13.3, '', ''],
       [2.2, 3.3, 4.4, 5.0],
       [12.2, 13.3, 14.4, 15.0],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]], dtype=object)

In [64]:
M[:,3]

array([5.2, '', 5.0, 15.0, nan, nan], dtype=object)

In [75]:
col1 = np.array([1,2]+[3,4, 5, 6])
col2 = np.array([5,6]+[7,8, 9, 0])

In [77]:
M[:,3] = col2

In [80]:
M[5,:]

array([nan, nan, nan, 0], dtype=object)

In [81]:
M.shape[0]

6

In [82]:
M.shape

(6, 4)

In [83]:
len(M)

6

In [84]:
A=np.array([2,2,2,2])
B=np.array([1,2,3,4])
A*B

array([2, 4, 6, 8])

In [85]:
A * 1/2

array([1., 1., 1., 1.])

In [87]:
np.square(A)/2

array([2., 2., 2., 2.])

In [107]:
COV

2     3     4  5
2   2.2   3.3   5.2  5
3  12.2  13.3        6
4   2.2   3.3   4.4  7
5  12.2  13.3  14.4  8
6   NaN   NaN   NaN  9
7   NaN   NaN   NaN  0

In [ ]:
M = COV